dynamic_snackbar : dynamic_snackbar.c
	gcc -g dynamic_snackbar.c -o dynamic_snackbar

repeat : repeat.c
	gcc -g repeat.c -o repeat

wordguess : wordguess.c
	gcc -g wordguess.c -o wordguess

all: dynamic_snackbar repeat wordguess
	

clean :
	rm wordguess repeat dynamic_snackbar 2> /dev/null

